version: '3.8'

services:
  flask-portfolio:
    image: buildwithdan/flask-portfolio:latest
    ports:
      - "6001:6001"
    volumes:
      - .:/flask-portfolio

      
    # environment:
    #   - FLASK_ENV=development
    # command: ["pipenv", "run", "flask", "--debug", "--app", "api/index.py", "run", "--host=0.0.0.0", "--port=6001"]
